language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: xenial
addons:
  apt:
    packages:
      - libvoikko-dev
      - unzip
before_install:
  - wget https://www.puimula.org/htp/testing/voikko-snapshot-v5/dict-morphoid.zip
  - sudo mkdir /etc/voikko
  - sudo unzip -d /etc/voikko dict-morphoid.zip
