name: Build + test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libvoikko dev package
      run: sudo apt-get install -y libvoikko-dev unzip voikko-fi
    - name: Install fi-x-morphoid dictionary
      run: |
        wget https://www.puimula.org/htp/testing/voikko-snapshot-v5/dict-morphoid.zip &&
        sudo mkdir /etc/voikko &&
        sudo unzip -d /etc/voikko dict-morphoid.zip
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
  check:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Run tarpaulin
      run: >
        cargo tarpaulin
        --ciserver github-actions
        --coveralls ${{ secrets.COVERALLS_TOKEN }}
